### ISSUE TITLE
Cannot Download on Mac M1

### ISSUE THREAD

**Issue by abadgerw** [ksugar/cellsparse-api#8]
@ksugar I am having issues downloading cellsparse on my Mac M1 using the instructions provided. I get the following error:
  
Building wheel for stardist-sparse (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for stardist-sparse (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [152 lines of output]
      <string>:4: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
      /private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/dist.py:488: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2025-Mar-03, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/version.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/rays3d.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/sample_patches.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/nms.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/matching.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/bioimageio_utils.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/utils.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      copying stardist/big.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist/plot
      copying stardist/plot/plot.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/plot
      copying stardist/plot/render.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/plot
      copying stardist/plot/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/plot
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist/models
      copying stardist/models/model3d.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/models
      copying stardist/models/model2d.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/models
      copying stardist/models/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/models
      copying stardist/models/base.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/models
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist/scripts
      copying stardist/scripts/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/scripts
      copying stardist/scripts/predict2d.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/scripts
      copying stardist/scripts/predict3d.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/scripts
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist/geometry
      copying stardist/geometry/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/geometry
      copying stardist/geometry/geom3d.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/geometry
      copying stardist/geometry/geom2d.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/geometry
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist/data
      copying stardist/data/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/stardist/data
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist/kernels
      copying stardist/kernels/stardist2d.cl -> build/lib.macosx-11.1-arm64-cpython-311/stardist/kernels
      copying stardist/kernels/stardist3d.cl -> build/lib.macosx-11.1-arm64-cpython-311/stardist/kernels
      creating build/lib.macosx-11.1-arm64-cpython-311/stardist/data/images
      copying stardist/data/images/mask2d.tif -> build/lib.macosx-11.1-arm64-cpython-311/stardist/data/images
      copying stardist/data/images/mask3d.tif -> build/lib.macosx-11.1-arm64-cpython-311/stardist/data/images
      copying stardist/data/images/img3d.tif -> build/lib.macosx-11.1-arm64-cpython-311/stardist/data/images
      copying stardist/data/images/img2d.tif -> build/lib.macosx-11.1-arm64-cpython-311/stardist/data/images
      copying stardist/data/images/histo.jpg -> build/lib.macosx-11.1-arm64-cpython-311/stardist/data/images
      running build_ext
      building 'stardist.lib.stardist2d' extension
      >>> compiling with '-fopenmp' failed
      building 'stardist.lib.stardist2d' extension
      >>> compiling with '-Xpreprocessor -fopenmp' failed
      >>> compiling with OpenMP support failed, re-trying without
      building 'stardist.lib.stardist2d' extension
      Traceback (most recent call last):
        File "/opt/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 80, in <module>
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 53, in build_extension
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 264, in build_extension
          _build_ext.build_extension(self, ext)
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/numpy/distutils/ccompiler.py", line 89, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
                                        ^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/numpy/distutils/ccompiler.py", line 272, in CCompiler_compile
          jobs = get_num_build_jobs()
                 ^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/numpy/distutils/misc_util.py", line 91, in get_num_build_jobs
          from numpy.distutils.core import get_distribution
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-build-env-xia83o31/overlay/lib/python3.11/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for stardist-sparse
  Building wheel for cellpose (setup.py) ... done
  Created wheel for cellpose: filename=cellpose-0.1.dev621+g5098105-py3-none-any.whl size=170599 sha256=0b99bf4b32336f24a8f2cd3024909dfdadd64a520a651db665f631442d56e0e7
  Stored in directory: /private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-ephem-wheel-cache-30twmsan/wheels/31/4b/46/91befb9700a702f1a673e1722ca9db17b37e6a8002bf53353c
  Building wheel for elephant (setup.py) ... done
  Created wheel for elephant: filename=elephant-0.5.2-py3-none-any.whl size=69492 sha256=a753c8f735ba35a9acc095b4521b6d0abcb9c33842dbe2af6b17efe752f8d636
  Stored in directory: /private/var/folders/pv/1b4v_5xx1zdcx6nfk94r99scvc5cld/T/pip-ephem-wheel-cache-30twmsan/wheels/a9/b1/bf/091cb728623cdf01d15767a8c88977adf5ff26dba7255f03b0
Successfully built cellsparse-api cellsparse cellpose elephant
Failed to build stardist-sparse
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (stardist-sparse)

**Comment by abadgerw** [comment]
@ksugar I downgraded python to 3.10 and was able to install. However, then I cannot launch the server and get the following error:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/cellsparse-api/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/uvicorn/main.py", line 412, in main
    run(
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/cellsparse_api/main.py", line 3, in <module>
    from cellsparse_api.routers import (
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/cellsparse_api/routers/cellpose_router.py", line 6, in <module>
    from cellsparse.runners import CellposeRunner
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/cellsparse/runners/__init__.py", line 2, in <module>
    from cellsparse.runners.stardist_runner import StarDistRunner
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/cellsparse/runners/stardist_runner.py", line 4, in <module>
    from stardist.models import (
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/stardist/__init__.py", line 15, in <module>
    from .geometry import star_dist,   polygons_to_label,   relabel_image_stardist, ray_angles, dist_to_coord
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/stardist/geometry/__init__.py", line 5, in <module>
    from .geom2d import star_dist, relabel_image_stardist, ray_angles, dist_to_coord, polygons_to_label, polygons_to_label_coord
  File "/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/stardist/geometry/geom2d.py", line 11, in <module>
    from ..lib.stardist2d import c_star_dist
ImportError: dlopen(/opt/anaconda3/envs/cellsparse-api/lib/python3.10/site-packages/stardist/lib/stardist2d.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '___kmpc_critical'
